name: Test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test-coverage
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.github_token }}
        path-to-profile: coverage.out
        parallel: true
        job-number: ${{ strategy.job-index }}
  finish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: finish coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
